name: Linux OS Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup
      run: sudo apt-get install make
    - name: setup
      run: sudo apt-get install libncurses5-dev libncursesw5-dev
    - name: make all
      run: make all -C 3_Implementation/
      
  
